### PR TITLE
doc(edge-node): security review repair — six blocker/high/medium findings

### PR DESCRIPTION
**Pull request by markdbodman**
## Summary

Post-implementation security review of the Edge Node spec surfaced six findings that need correction before the spec is treated as security-approved. This PR addresses all six. **No code change — spec text only.**

### Blocker — "machine-bound" token language is not true for Phase 0

The spec called the `dpfedge_*` token "machine-bound" in multiple places, but Phase 0 transports it as a bearer credential over HTTPS with no DPoP / mTLS / platform-attested keypair. A copied token impersonates the node until rotation.

**Fix:** the spec now calls it a **"per-node bearer"**, documents the Phase 0 compensating controls (short TTL, heartbeat rotation, audit, no re-enrollment shortcut), and lists the Phase 1+ upgrade path (mTLS / DPoP / TPM / Secure Enclave). The Mobile-vs-EdgeNode disambiguation table, Token Model section, Refresh row, and R&B comparator paragraph all updated.

### Blocker — Principal convergence consistency

Verified end-to-end. No remaining `EdgeNode.displayName` references; no `"edge-node"` (hyphen) string-value references; the schema block at "Edge Node registry" already uses `principalId @unique` per the 2026-05-12 retrofit (#500). Mark's review cited line numbers from an earlier snapshot — the current `main` already honors convergence; this PR's job is to keep that and address the remaining five issues.

### High — ingestion attribution could be spoofed by a body `nodeId`

The earlier draft envelope for `POST /api/v1/edge/discovery-runs` included `"nodeId"` in the request body. A node holding a valid token for Edge Node A could claim observations from B by shadowing the body field.

**Fix:** explicit **"Identity attribution rule (CRITICAL)"** clause: `edgeNodeId`, `nodeId`, `principalId`, `sourceSlug` derive exclusively from `resolveEdgeNodeAuth`. The canonical envelope omits identity fields. If a future revision re-introduces a body `nodeId` for diagnostic echo, the server rejects mismatches with `401 nodeId_mismatch`. The current implementation in `apps/web/app/api/v1/edge/discovery-runs/route.ts` already honors this — the spec text now matches.

### High — REST ingestion drops MCP governance without replacing the controls

The spec said MCP would have provided governance, audit, and rate-limiting "by construction," then chose REST first for Phase 0 without specifying equivalents.

**Fix:** new **"REST ingestion controls (Phase 0)"** subsection. Binding for Phase 0:

| Control | Phase 0 default |
|---|---|
| Per-node rate limit (heartbeat) | 12 req/min, burst 5 req/sec for 10s |
| Per-node rate limit (discovery) | 4 req/min, 60 req/hour sustained |
| `items` cap | 10,000 entries per run |
| `relationships` cap | 20,000 entries per run |
| `rawData` per item | <= 64 KB |
| Total request body | <= 5 MB (413 before parse) |
| Run idempotency | `(edgeNodeId, runKey)` unique; re-submission returns prior result |
| Replay window for bearer token | <= heartbeat interval + grace window (~1h) |
| Failure audit | 401 / 403 / 429 / 5xx all write `ToolExecution`, no bearer plaintext |
| Freshness window | `observedAt` within +/- 24h of server time |

**Phase 0 schema follow-up flagged:** `DiscoveryRun.runKey @unique` must become `@@unique([runKey, edgeNodeId])` for the idempotency contract. Small migration PR after this lands.

### High — secure storage was contradictory

Spec said tokens are "never written to plaintext config." The merged service skeleton in `services/edge-node/src/state.ts` stores the `dpfedge_*` token at `/var/lib/dpf-edge-node/state.json` (chmod 0600).

**Fix:** new **"Phase 0 storage downgrade (Linux container Mode 1)"** subsection. Documents the fallback as an explicit downgrade with binding controls:

- Non-root dedicated UID (`dpf:dpf`), chowned at image build
- 0600 enforced at write, verified at read (umask drift)
- Docker-managed volume, **never** host bind-mount
- **No Docker socket mount** in the Edge Node container
- Backup tooling excludes / redacts `state.json`
- Binary never logs `nodeToken` in plaintext (unit-test enforced)
- Operator-triggered rotation on suspected copy
- Per-node state directory; cross-node mounting refused via fingerprint check

Modes 2 (native macOS / Windows) and 4 (TPM-attested, Phase 1+) bypass the downgrade entirely.

### Medium — quarantine semantics had Phase 0 vs Phase 1+ collision

The Quarantine section listed four triggers (manual + 3 automatic) but elsewhere said Phase 0 is manual-only.

**Fix:** explicit split:

- **Phase 0 contract:** manual operator action is the **only** trigger. Implementations and tests rely on this exact contract. No anomaly wiring, no re-attestation polling, no heartbeat-miss timer.
- **Phase 1+ planned triggers (out of Phase 0 scope):** anomaly detection on submission deltas, re-attestation drift (binary signature, host fingerprint), missed-heartbeat timer. Each requires its own design slice + security review before implementation.

The "Binary tampering" finding in the Important security list now explicitly notes that auto-quarantine on signature mismatch is Phase 1+, not Phase 0.

## Security review summary updated

The Critical / Important / Acceptable lists in the spec now match the corrections above:

- **New Critical:** token impersonation by copy (Phase 0 risk with compensating controls; **moves to "must close" before Phase 2 macOS native** because that's the path most plausibly handling tokens that escape the container boundary).
- **New Critical:** ingestion attribution by body (closed by the rule above).
- **Updated Important:** soft-fail abuse + binary tampering now flag Phase 0 vs Phase 1+ scope explicitly.
- **New Important:** REST ingestion controls (the binding list above).
- **New Acceptable:** Phase 0 bearer-token replay during rotation window — closed structurally by Phase 1+ token binding.

## Test plan

- [x] No remaining `"edge-node"` (hyphen) string-value references
- [x] No remaining `EdgeNode.displayName` references
- [x] No remaining unqualified "machine-bound" claims (the three remaining mentions are all in the spec's own self-aware downgrade language explaining what was changed)
- [x] Revision history updated with the six findings + the corrections
- [ ] Reviewer agreement on the per-node rate-limit defaults
- [ ] Reviewer agreement on the freshness window (+/- 24h)
- [ ] Reviewer agreement on rotation-grace window (~1h) being the Phase 0 acceptable replay risk

## Diff shape

Single file: `docs/superpowers/specs/2026-05-09-dpf-edge-node-design.md`. ~346 lines added, ~48 removed.

## Note on #500's CI

Mark's review flagged: "#500 shows merged even though its PR check rollup reported Unit Tests failure. ... worth following up because this stack is security-sensitive."

I verified the Unit Tests failure on PR #500 against current `origin/main` (with my changes stashed and the migration removed): identical failures in `lib/mcp-tools-backlog.test.ts` and `lib/mcp-tools-save-build-evidence.test.ts` with the same error — `"Cannot find module 'next/server' imported from next-auth/lib/env.js"`. The failures are a next-auth + Next 16 + vitest module-resolution issue in the test infrastructure, not introduced by #500.

That said, **Mark's point stands**: a security-sensitive stack shouldn't be merging through red. A separate follow-up PR should either (a) fix the next-auth import path in the test setup or (b) restore the test-infrastructure invariant that protects against red merges. Filed as a separate concern from this spec repair.

## Related

- AGENTS.md §11 — Principal convergence rule (already honored)
- PR #500 — convergence retrofit (merged 2026-05-12)
- PR #503 — alias-form alignment (merged 2026-05-12)
- PR #498 — Authority API endpoints (merged 2026-05-12)
- PR #499 — `persistSubmittedDiscoveryRun` (merged 2026-05-12)
- PR #501 — Edge Node service skeleton (merged 2026-05-12; storage downgrade controls bind this implementation)

### CODE REVIEW

**Comment by markdbodman** [comment]
## Response to security review

Two of the six findings were real bugs in this PR and are now fixed in commit c57d6e71:

- **P1 — orphan `edge:register` scope:** the token-model scope list still showed `edge:register` while every other reference (and the implementation in PR #498) used `edge:enroll`. Renamed; added explicit comments on the canonical scope vocabulary.
- **P1 — runtime-language drift:** the deployment-modes table still framed the native-binary path as "(~5 MB, Go or Rust)" but Phase 0 Mode 1 shipped Node.js / TypeScript via PR #501. The drift is now documented in the table and in a reclassified open-question resolution — `(durable)` → `(open — drift documented)` — with two acceptable paths forward and a note that the decision must land before Mode 2 macOS native ships.

The other four findings appear to be looking at the original research stub (PR #400 commit `6e40127b`), not this PR's content:

### Evidence

The line numbers cited in the review match the original research stub, not the current spec on main, and definitely not this PR's head:

| Cited line | Cited content | What it actually is in PR #400 stub | What it is at this PR head |
|---|---|---|---|
| L1 | "DRAFT / RESEARCH" | `# DPF Edge Node and Discovery Plane Architecture (DRAFT / RESEARCH)` | `# DPF Edge Node and Discovery Plane Architecture` (header says **Status: binding**) |
| L432 | EdgeNode with displayName, no principalId | `## Edge Node registry (proposed Prisma models)` | Middle of the Phase 0 storage-downgrade subsection I added in this PR |
| L141 | Go/Rust binary framed open | `Statically-linked binary (~5 MB, Go or Rust)` in the modes table | After this PR's pass 2: rewritten with the runtime-drift acknowledgement (commit c57d6e71) |
| L667 | "R&B as TBD" | `## Research and Benchmarking (TBD per AGENTS.md §10)` | A line inside the existing R&B section (filled in by #491) |
| L711 | maturity gates unchecked | `- [ ] Research & Benchmarking section complete` | `EdgeNodeCapability` model definition end + ingestion contract header |

### Reconciling commands

If your local `origin/main` is up to date and you re-fetch this PR, you should see:

```
$ git fetch origin && git checkout doc/edge-node-spec-security-repair && git diff --shortstat origin/main -- docs/superpowers/specs/2026-05-09-dpf-edge-node-design.md
 1 file changed, 419 insertions(+), 69 deletions(-)

$ sed -n 1p docs/superpowers/specs/2026-05-09-dpf-edge-node-design.md
# DPF Edge Node and Discovery Plane Architecture

$ sed -n 3p docs/superpowers/specs/2026-05-09-dpf-edge-node-design.md
> Status: **binding** as of 2026-05-12. The maturity gates from the
```

GitHub's PR view also confirms: <https://github.com/OpenDigitalProductFactory/opendigitalproductfactory/pull/509/files> shows +419 / -69 on this single file (after pass 2). The 669-deletion delta in the review doesn't match — likely a stale-cache or wrong-base comparison in whichever review tool produced it.

### The other findings are addressed in the PR text

Each was already corrected in the initial commit (c8ffbe25) and the pass-2 commit further reinforces them:

- **Principal convergence:** the schema block at lines ~504–536 of the spec uses `principalId @unique` and has no `displayName` on `EdgeNode`. The convergence layout at lines ~461–476 enumerates `Principal { kind: "edge_node" }` + `PrincipalAlias { aliasType: "edge_node" }` + `EdgeNode { principalId @unique }`. (Honored on `main` since #500 + #503.)
- **Machine-bound overclaim:** downgraded to "per-node bearer" in the Mobile-vs-Edge disambiguation table, Token Model section, Refresh row, and R&B comparator. Added explicit Phase 0 token-binding posture subsection with compensating controls and the Phase 1+ upgrade path.
- **Body `nodeId` attribution:** new "Identity attribution rule (CRITICAL)" clause in the ingestion contract — `edgeNodeId / nodeId / principalId / sourceSlug` come from `resolveEdgeNodeAuth` only.
- **REST governance:** new "REST ingestion controls (Phase 0)" subsection — per-node rate limits, payload caps, `(edgeNodeId, runKey)` idempotency, failure audit, freshness window.

### What I'd like

Could you re-fetch and re-run the diff against this PR's current HEAD (`c57d6e71`)? If your review tool is still showing the 669-deletion regression, that's a tooling issue worth filing separately — and I'd rather find out before merge than after.
